/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlythuvien.view.panel;

import com.mycompany.quanlythuvien.model.BanDoc;
import com.mycompany.quanlythuvien.dao.ChiTietPhieuMuonDAO;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DMX MSI
 */
public class ChiTietPhieuBanDocPanel extends javax.swing.JPanel {
    private CardLayout cardLayout;
    private BanDoc cur;
    
    
    void loadPhieuMuon() throws Exception {
        DefaultTableModel model = (DefaultTableModel) tblPhieuMuon.getModel();
        model.setRowCount(0); // xóa dữ liệu cũ

        if (cur == null) {
            System.out.println("BanDoc null -> không load phiếu mượn");
            return;
        }

        ChiTietPhieuMuonDAO qr = new ChiTietPhieuMuonDAO();
        ArrayList<Object> arr = qr.getAllPhieuMuonBanDoc(cur);

        if (arr == null || arr.isEmpty()) {
            // không có dữ liệu
            return;
        }

        int fieldsPerRecord = 8;
        if (arr.size() % fieldsPerRecord != 0) {
            System.out.println("Warning: arr.size() không chia hết cho 8: " + arr.size());
        }
        for (int i = 0; i + fieldsPerRecord - 1 < arr.size(); i += fieldsPerRecord) {
            Object idPM = arr.get(i);
            Object emailNguoiLap = arr.get(i + 1);
            Object ngayMuon = arr.get(i + 2);
            Object hanTra = arr.get(i + 3);
            Object maBanSao = arr.get(i + 4);
            Object ngayTraThucTe = arr.get(i + 5);
            Object tinhTrang = arr.get(i + 6);
            Object emailNguoiNhan = arr.get(i + 7);

            // Nếu muốn format riêng các LocalDate -> String, có thể làm ở đây:
            // (nhưng DefaultTableModel hiển thị LocalDate.toString() cũng ok)
            model.addRow(new Object[] {
                idPM,
                emailNguoiLap,
                ngayMuon,
                hanTra,
                maBanSao,
                ngayTraThucTe,
                tinhTrang,
                emailNguoiNhan
            });
        }
    }
    
    void loadPhieuPhat() throws Exception {
        DefaultTableModel model = (DefaultTableModel) tblPhieuPhat.getModel();
        model.setRowCount(0); // xóa dữ liệu cũ

        if (cur == null) {
            System.out.println("BanDoc null -> không load phiếu phạt");
            return;
        }

        ChiTietPhieuMuonDAO qr = new ChiTietPhieuMuonDAO();
        ArrayList<Object> arr = qr.getAllPhieuPhatBanDoc(cur);

        if (arr == null || arr.isEmpty()) {
            // không có dữ liệu
            return;
        }

        int fieldsPerRecord = 8; // tương ứng với DAO trả về 8 giá trị/record
        if (arr.size() % fieldsPerRecord != 0) {
            System.out.println("Warning: arr.size() không chia hết cho 8: " + arr.size());
        }
        for (int i = 0; i + fieldsPerRecord - 1 < arr.size(); i += fieldsPerRecord) {
            Object idPhat = arr.get(i);
            Object idPM = arr.get(i + 1);
            Object emailNguoiLap = arr.get(i + 2);
            Object ngayMuon = arr.get(i + 3);
            Object loaiPhat = arr.get(i + 4);
            Object soTien = arr.get(i + 5);
            Object ngayGhiNhan = arr.get(i + 6);
            Object trangThai = arr.get(i + 7);

            // Nếu muốn format LocalDate -> String (ví dụ dd/MM/yyyy) bạn có thể chuyển ở đây.
            model.addRow(new Object[] {
                idPhat,
                idPM,
                emailNguoiLap,
                ngayMuon,
                loaiPhat,
                soTien,
                ngayGhiNhan,
                trangThai
            });
        }
    }



    /**
     * Creates new form ChiTietPhieuBanDocPanel
     */
    public ChiTietPhieuBanDocPanel() {
        initComponents();
    }
    public ChiTietPhieuBanDocPanel(BanDoc x) throws Exception {
        initComponents(); 
        cur = x;
        cardLayout = (CardLayout) pnlCards.getLayout();
        cardLayout.show(pnlCards, "PHIEU_MUON");
        btnPhieuMuon.setSelected(true);
        btnPhieuMuon.setSelected(false);
        loadPhieuMuon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnPhieuMuon = new javax.swing.JToggleButton();
        btnPhieuPhat = new javax.swing.JToggleButton();
        pnlCards = new javax.swing.JPanel();
        cardPhieuPhat = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhieuPhat = new javax.swing.JTable();
        cardPhieuMuon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuMuon = new javax.swing.JTable();

        buttonGroup1.add(btnPhieuMuon);
        btnPhieuMuon.setText("Phiếu Phạt");
        btnPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuMuonActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnPhieuPhat);
        btnPhieuPhat.setText("Phiếu Phạt");
        btnPhieuPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuPhatActionPerformed(evt);
            }
        });

        pnlCards.setLayout(new java.awt.CardLayout());

        tblPhieuPhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Phiếu Phạt", "ID Phiếu Mượn", "Email Thủ Thư Lập", "Ngày Mượn", "Loại Phạt", "Số Tiền", "Ngày Ghi Nhận", "Trạng Thái Đóng"
            }
        ));
        jScrollPane2.setViewportView(tblPhieuPhat);

        javax.swing.GroupLayout cardPhieuPhatLayout = new javax.swing.GroupLayout(cardPhieuPhat);
        cardPhieuPhat.setLayout(cardPhieuPhatLayout);
        cardPhieuPhatLayout.setHorizontalGroup(
            cardPhieuPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPhieuPhatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardPhieuPhatLayout.setVerticalGroup(
            cardPhieuPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPhieuPhatLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pnlCards.add(cardPhieuPhat, "PHIEU_PHAT");

        tblPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Phiếu Mượn", "Email Thủ Thư Lập", "Ngày Mượn", "Hạn Trả", "Mã Bản Sao", "Ngày Trả", "Tình Trạng Khi Trả", "Email Thủ Thư Nhận"
            }
        ));
        jScrollPane1.setViewportView(tblPhieuMuon);

        javax.swing.GroupLayout cardPhieuMuonLayout = new javax.swing.GroupLayout(cardPhieuMuon);
        cardPhieuMuon.setLayout(cardPhieuMuonLayout);
        cardPhieuMuonLayout.setHorizontalGroup(
            cardPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPhieuMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardPhieuMuonLayout.setVerticalGroup(
            cardPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPhieuMuonLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pnlCards.add(cardPhieuMuon, "PHIEU_MUON");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(528, 528, 528)
                .addComponent(btnPhieuMuon)
                .addGap(5, 5, 5)
                .addComponent(btnPhieuPhat))
            .addComponent(pnlCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPhieuMuon)
                    .addComponent(btnPhieuPhat))
                .addGap(5, 5, 5)
                .addComponent(pnlCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuMuonActionPerformed
        btnPhieuMuon.setSelected(true);
        btnPhieuPhat.setSelected(false);
        cardLayout.show(pnlCards, "PHIEU_MUON");
        try {
            // nếu muốn load dữ liệu khi chuyển:
            loadPhieuMuon();
        } catch (Exception ex) {
            System.getLogger(ChiTietPhieuBanDocPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnPhieuMuonActionPerformed

    private void btnPhieuPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuPhatActionPerformed
        btnPhieuMuon.setSelected(false);
        btnPhieuPhat.setSelected(true);
        cardLayout.show(pnlCards, "PHIEU_PHAT");
        // nếu muốn load dữ liệu khi chuyển:
        try {
            loadPhieuPhat();
        } catch (Exception ex) {
            System.getLogger(ChiTietPhieuBanDocPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnPhieuPhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnPhieuMuon;
    private javax.swing.JToggleButton btnPhieuPhat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cardPhieuMuon;
    private javax.swing.JPanel cardPhieuPhat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JTable tblPhieuMuon;
    private javax.swing.JTable tblPhieuPhat;
    // End of variables declaration//GEN-END:variables
}
