/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlythuvien.view.panel;

import com.mycompany.quanlythuvien.controller.BanDocController;
import com.mycompany.quanlythuvien.model.BanDoc;
import java.awt.Frame;
import java.util.*;
import java.util.stream.Collectors;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DMX MSI
 */
public class QuanLyBanDocPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyBanDocPanel
     */
    BanDocController cur;
    String txtSearchPrv = "";
    public QuanLyBanDocPanel() throws Exception {
        initComponents();
        cur = new BanDocController();
        try {
            cur.init();
            showList(cur.getDsBanDoc());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi load dữ liệu:\n" + ex.getMessage());
        }
    }
    private ArrayList<BanDoc> filterList(String KEYFIELD, String KEYTXT) {
        ArrayList<BanDoc> newDsBanDoc = new ArrayList<BanDoc>(); 
        
        switch(KEYFIELD) {
            case "Họ Tên":
                newDsBanDoc = (ArrayList<BanDoc>) cur.getDsBanDoc().stream()
                            .filter(x -> x.getHoTen() != null && x.getHoTen().toLowerCase().startsWith(KEYTXT))
                            .collect(Collectors.toList());
                break;

            case "Email":
                newDsBanDoc = (ArrayList<BanDoc>) cur.getDsBanDoc().stream()
                            .filter(x -> x.getEmail() != null && x.getEmail().toLowerCase().startsWith(KEYTXT))
                            .collect(Collectors.toList());
                break;

            case "SĐT":
                newDsBanDoc = (ArrayList<BanDoc>) cur.getDsBanDoc().stream()
                            .filter(x -> x.getSdt() != null && x.getSdt().toLowerCase().startsWith(KEYTXT))
                            .collect(Collectors.toList());
                break;

            case "Địa Chỉ":
                newDsBanDoc = (ArrayList<BanDoc>) cur.getDsBanDoc().stream()
                            .filter(x -> x.getDiaChi() != null && x.getDiaChi().toLowerCase().startsWith(KEYTXT))
                            .collect(Collectors.toList());
                break;
            case "ID":
                newDsBanDoc = (ArrayList<BanDoc>) cur.getDsBanDoc().stream()
                            .filter(x -> Integer.toString(x.getIdBD()).startsWith(KEYTXT))
                            .collect(Collectors.toList());
                break;
        }
        return newDsBanDoc;
    }
    private void showList(ArrayList<BanDoc> list) {
        String[] cols = {"ID", "Họ tên", "Email", "SDT", "Địa chỉ"};

        DefaultTableModel model = new DefaultTableModel(cols, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) return Integer.class;
                return String.class;
            }
        };

        if (list != null) {
            for (BanDoc bd : list) {
                Object[] row = new Object[] {
                    bd.getIdBD(),
                    bd.getHoTen(),
                    bd.getEmail(),
                    bd.getSdt(),
                    bd.getDiaChi()
                };
                model.addRow(row);
            }
        }

        tblUsers.setModel(model);
        tblUsers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblUsers.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        Search = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        searchByCombo = new javax.swing.JComboBox<>();
        scrollPaneUsers = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        jToolBar1.setRollover(true);

        btnAdd.setText("ADD");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);

        btnEdit.setText("EDIT");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);

        btnDelete.setText("DELETE");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);

        btnView.setText("View");
        jToolBar1.add(btnView);

        Search.setText("Search:");
        jToolBar1.add(Search);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jToolBar1.add(txtSearch);

        searchByCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Họ Tên", "Email", "SĐT", "Địa Chỉ" }));
        searchByCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByComboActionPerformed(evt);
            }
        });
        jToolBar1.add(searchByCombo);

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ tên", "Email", "SDT", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPaneUsers.setViewportView(tblUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPaneUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        BanDocFormDialog dlg = new BanDocFormDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
        if (dlg.isSaved()) {
            BanDoc newBd = dlg.getBanDoc();
            System.out.println(newBd.getHoTen());
            try {
                cur.add(newBd); 
            } catch (Exception ex) {
                
            }
            showList(cur.getDsBanDoc());
            JOptionPane.showMessageDialog(this, "Thêm bạn đọc thành công.");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int viewRow = tblUsers.getSelectedRow();
        if (viewRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 bạn đọc để xóa.", "Chú ý", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int modelRow = tblUsers.convertRowIndexToModel(viewRow);
        Object idObj = tblUsers.getModel().getValueAt(modelRow, 0);
        Object nameObj = tblUsers.getModel().getValueAt(modelRow, 1);
        Object emailObj = tblUsers.getModel().getValueAt(modelRow, 2);
        Object sdtObj = tblUsers.getModel().getValueAt(modelRow, 3);
        Object diaChiObj = tblUsers.getModel().getValueAt(modelRow, 4);

        final String id = nameObj == null ? "" : idObj.toString();
        final String name = nameObj == null ? "" : nameObj.toString();
        final String email = emailObj == null ? "" : emailObj.toString();
        final String sdt = sdtObj == null ? "" : sdtObj.toString();
        final String diaChi = diaChiObj == null ? "" : diaChiObj.toString();

        int choice = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xóa bạn đọc:\n" +
                "ID: " + id + "\n" +        
                "Họ tên: " + name + "\n" +
                "Email: " + email + "\n" +
                "SĐT: " + sdt + "\n" +
                "Địa chỉ: " + diaChi,
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (choice != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            BanDoc bdToDelete = new BanDoc();
            bdToDelete.setIdBD(Integer.parseInt(id));
            bdToDelete.setHoTen(name);
            bdToDelete.setEmail(email);
            bdToDelete.setSdt(sdt);
            bdToDelete.setDiaChi(diaChi);

            boolean deleted = false;

            try {

                deleted = cur.delete(bdToDelete); 
            } catch (NoSuchMethodError | AbstractMethodError err) {

            }

            if (deleted) {
                showList(cur.getDsBanDoc());
                JOptionPane.showMessageDialog(this, "Xóa thành công.", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy bản ghi phù hợp hoặc xóa thất bại.", "Thất bại", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa:\n" + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        String fieldSearchCur = searchByCombo.getSelectedItem().toString();
        String txtSearchCur = txtSearch.getText().toString().toLowerCase().trim();
        if(txtSearchCur.equals("")) {
            showList(cur.getDsBanDoc());
            return;
        }
        if(txtSearchCur != txtSearchPrv) {
            showList(filterList(fieldSearchCur, txtSearchCur));
            txtSearchPrv = txtSearchCur;
        }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void searchByComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByComboActionPerformed
        if(txtSearchPrv.equals("")) return;
        String fieldSearchCur = searchByCombo.getSelectedItem().toString();
     
        showList(filterList(fieldSearchCur, txtSearchPrv.toLowerCase().trim()));
        
    }//GEN-LAST:event_searchByComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Search;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnView;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane scrollPaneUsers;
    private javax.swing.JComboBox<String> searchByCombo;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
