/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlythuvien.view.panel;

import com.mycompany.quanlythuvien.controller.SachController;
import com.mycompany.quanlythuvien.dialog.ThongTinSachDialog;
import com.mycompany.quanlythuvien.dialog.DanhSachBanSaoDialog;
import com.mycompany.quanlythuvien.model.Sach;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuanLySachPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLySachPanel
     */
    private DefaultTableModel tableModel = new DefaultTableModel();
    private SachController sachController = new SachController();
    
    public QuanLySachPanel() {
        initComponents();
        initTable();
        loadDataToTable();
        initComboBox();
        tblSach.setRowHeight(28);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTimKiem = new javax.swing.JLabel();
        cboTieuChi = new javax.swing.JComboBox<>();
        txtTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        btnXemBanSao = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTimKiem.setText("Tìm kiếm sách");
        jPanel2.add(lblTimKiem);

        cboTieuChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboTieuChi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboTieuChi);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel2.add(txtTimKiem);

        btnTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        jPanel2.add(btnTim);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        tblSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Tên", "Tác giả", "Nhà xuất bản", "Năm", "Thể loại"
            }
        ));
        jScrollPane1.setViewportView(tblSach);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem);

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua);

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa);

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnLamMoi);

        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChiTiet.setText("Xem chi tiết");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        jPanel1.add(btnChiTiet);

        btnXemBanSao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXemBanSao.setText("Xem bản sao");
        btnXemBanSao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemBanSaoActionPerformed(evt);
            }
        });
        jPanel1.add(btnXemBanSao);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void initTable() {
        tableModel.setColumnIdentifiers(new String[]{
            "ISBN", "Tên sách", "Tác giả", "Nhà xuất bản", "Năm", "Thể loại"
        });
        tblSach.setModel(tableModel);
    }
    
    private void loadDataToTable() {
        try {
            List<Sach> list = sachController.getAllForTable();
            tableModel.setRowCount(0);
            
            for (Sach s : list) {
                tableModel.addRow(new Object[]{
                    s.getISBN(),
                    s.getTenSach(),
                    s.getTenTacGia(),
                    s.getTenNXB(),
                    s.getNamXuatBan(),
                    s.getTenTheLoai()
                });
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu: " + e.getMessage());
        }
    }
    
    private void initComboBox(){
        cboTieuChi.removeAllItems();
        cboTieuChi.addItem("Tất cả");
        cboTieuChi.addItem("Tên sách");
        cboTieuChi.addItem("Tác giả");
        cboTieuChi.addItem("Nhà xuất bản");
        cboTieuChi.addItem("Thể loại");
        cboTieuChi.addItem("ISBN");
    }
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        //sach=null, isEditMode=false
        ThongTinSachDialog dialog = new ThongTinSachDialog(null, true, null, false, false);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        loadDataToTable();
    }//GEN-LAST:event_btnThemActionPerformed

    //lay ISBN o dong da chon, truyen ISBN vao de dialog load du lieu, sau khi luu -> Reload
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int r = tblSach.getSelectedRow();
        if (r == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách để sửa");
            return;
        }

        String isbn = (String) tableModel.getValueAt(r, 0);
        try {
            Sach sach = sachController.findByISBN(isbn); // lay thon tin sach
            if (sach != null) {
                ThongTinSachDialog dialog = new ThongTinSachDialog(null, true, sach, true, false); // sua: truyen sach, isEditMode=true
                dialog.setLocationRelativeTo(this);
                dialog.setVisible(true);
                loadDataToTable();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải sách: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int r = tblSach.getSelectedRow();
        if (r == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách để xóa");
            return;
        }
        
        String isbn = (String) tableModel.getValueAt(r, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "Xóa sách " + isbn + "?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (sachController.delete(isbn)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    loadDataToTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        loadDataToTable();
        txtTimKiem.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        int r = tblSach.getSelectedRow();
        if (r == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách để xem chi tiết!");
            return;
        }
        
        String isbn = (String) tableModel.getValueAt(r, 0);
        try {
            Sach sach = sachController.findByISBN(isbn);
            if (sach != null) {
                ThongTinSachDialog dialog = new ThongTinSachDialog(null, true, sach, false, true);
                dialog.setLocationRelativeTo(this);
                dialog.setVisible(true);
                //loadDataToTable();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải chi tiết sách" + e.getMessage());
        }
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void btnXemBanSaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemBanSaoActionPerformed
        // TODO add your handling code here:
        int r = tblSach.getSelectedRow();   
        if (r == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sách để xem bản sao");
            return;
        }
        String isbn = (String) tableModel.getValueAt(r, 0);
        DanhSachBanSaoDialog dialog = new DanhSachBanSaoDialog(null, true, isbn);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnXemBanSaoActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:      
        try {
            String keyword = txtTimKiem.getText().trim();
            String tieuChi = cboTieuChi.getSelectedItem().toString();
            
            List<Sach> list = sachController.search(keyword, tieuChi);
           
            tableModel.setRowCount(0);
            
            for (Sach s : list) {
                tableModel.addRow(new Object[] {
                    s.getISBN(),
                    s.getTenSach(),
                    s.getTenTacGia(),
                    s.getTenNXB(),
                    s.getNamXuatBan(),
                    s.getTenTheLoai()
                });
            }
            
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sách nào!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXemBanSao;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboTieuChi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
