package com.mycompany.quanlythuvien.view;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JPanel;

import com.mycompany.quanlythuvien.model.TaiKhoan;
import com.mycompany.quanlythuvien.view.panel.QuanLyBanDocPanel;
import com.mycompany.quanlythuvien.view.panel.QuanLyPhieuMuonPanel;
import com.mycompany.quanlythuvien.view.panel.QuanLySachPanel;
import com.mycompany.quanlythuvien.view.panel.QuanLyTaiKhoanPanel;
import com.mycompany.quanlythuvien.view.panel.ThongKePanel;
import com.mycompany.quanlythuvien.view.panel.WelcomePanel;

/**
 *
 * @author Tien
 */
public class JFrame_Main extends javax.swing.JFrame {

    private TaiKhoan currentUser;

    /**
     * Creates new form JFrame_Main
     */
    private CardLayout cardLayout;
    
    public JFrame_Main(TaiKhoan user) {
        initComponents();
        this.currentUser = user;

        this.setLocationRelativeTo(null);
        jLabel_Welcome.setText("<html><div style='text-align: center;'>Xin chào,<br/>" + currentUser.getHoTen() + "!</div></html>");

        // Cài đặt CardLayout
        setupCardLayout();
        
        // Thêm action listener cho nút Quản Lý Bạn Đọc
        jButton_QuanLyBanDoc.addActionListener(evt -> {
            cardLayout.show(jPanel_Content, "QuanLyBanDoc");
        });

        authorizeRoles();
    }

    private void setupCardLayout() {
        cardLayout = new CardLayout();
        jPanel_Content.setLayout(cardLayout);
        
        // Thêm các panel vào CardLayout
        jPanel_Content.add(new WelcomePanel(), "Welcome");
        jPanel_Content.add(new QuanLySachPanel(), "QuanLySach");
        jPanel_Content.add(new QuanLyBanDocPanel(), "QuanLyBanDoc");
        jPanel_Content.add(new QuanLyPhieuMuonPanel(), "QuanLyPhieuMuon");
        jPanel_Content.add(new ThongKePanel(), "ThongKe");
        jPanel_Content.add(new QuanLyTaiKhoanPanel(), "QuanLyTaiKhoan");
        
        // Hiển thị panel chào mừng mặc định
        cardLayout.show(jPanel_Content, "Welcome");
        
        // Thêm hiệu ứng hover cho các nút menu
        addHoverEffect(jButton_QuanLySach);
        addHoverEffect(jButton_QuanLyBanDoc);
        addHoverEffect(jButton_QuanLyPhieuMuon);
        addHoverEffect(jButton_ThongKe);
        addHoverEffect(jButton_QuanLyTaiKhoan);
    }
    
    private void addHoverEffect(javax.swing.JButton button) {
        Color defaultColor = new Color(51, 51, 51);
        Color hoverColor = new Color(70, 70, 70);
        
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (button.isVisible()) {
                    button.setBackground(hoverColor);
                }
            }
            
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(defaultColor);
            }
        });
    }

    private void authorizeRoles() {
        String role = currentUser.getRole();

        if (role == null) {
            jButton_QuanLySach.setVisible(false);
            jButton_QuanLyBanDoc.setVisible(false);
            jButton_QuanLyPhieuMuon.setVisible(false);
            jButton_QuanLyTaiKhoan.setVisible(false);
            jButton_ThongKe.setVisible(false);
            return;
        }

        switch (role) {
            case "Admin":
                break;
            case "ThuThu":
                jButton_QuanLyTaiKhoan.setVisible(false);
                break;
            default:
                jButton_QuanLySach.setVisible(false);
                jButton_QuanLyBanDoc.setVisible(false);
                jButton_QuanLyPhieuMuon.setVisible(false);
                jButton_QuanLyTaiKhoan.setVisible(false);
                jButton_ThongKe.setVisible(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Menu = new javax.swing.JPanel();
        jLabel_Welcome = new javax.swing.JLabel();
        jButton_QuanLyBanDoc = new javax.swing.JButton();
        jButton_QuanLyPhieuMuon = new javax.swing.JButton();
        jButton_QuanLySach = new javax.swing.JButton();
        jButton_ThongKe = new javax.swing.JButton();
        jButton_QuanLyTaiKhoan = new javax.swing.JButton();
        jButton_Logout = new javax.swing.JButton();
        jPanel_Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");

        jPanel_Menu.setBackground(new java.awt.Color(51, 51, 51));

        jLabel_Welcome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel_Welcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Welcome.setText("Xin chào");

        jButton_QuanLyBanDoc.setBackground(new java.awt.Color(51, 51, 51));
        jButton_QuanLyBanDoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_QuanLyBanDoc.setForeground(new java.awt.Color(255, 255, 255));
        jButton_QuanLyBanDoc.setText("Quản Lý Bạn Đọc");
        jButton_QuanLyBanDoc.setBorder(null);
        jButton_QuanLyBanDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton_QuanLyPhieuMuon.setBackground(new java.awt.Color(51, 51, 51));
        jButton_QuanLyPhieuMuon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_QuanLyPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        jButton_QuanLyPhieuMuon.setText("Quản Lý Phiếu Mượn");
        jButton_QuanLyPhieuMuon.setBorder(null);
        jButton_QuanLyPhieuMuon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_QuanLyPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QuanLyPhieuMuonActionPerformed(evt);
            }
        });

        jButton_QuanLySach.setBackground(new java.awt.Color(51, 51, 51));
        jButton_QuanLySach.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_QuanLySach.setForeground(new java.awt.Color(255, 255, 255));
        jButton_QuanLySach.setText("Quản Lý Sách");
        jButton_QuanLySach.setBorder(null);
        jButton_QuanLySach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_QuanLySach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QuanLySachActionPerformed(evt);
            }
        });

        jButton_ThongKe.setBackground(new java.awt.Color(51, 51, 51));
        jButton_ThongKe.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_ThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ThongKe.setText("Thống Kê");
        jButton_ThongKe.setBorder(null);
        jButton_ThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThongKeActionPerformed(evt);
            }
        });

        jButton_QuanLyTaiKhoan.setBackground(new java.awt.Color(51, 51, 51));
        jButton_QuanLyTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_QuanLyTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        jButton_QuanLyTaiKhoan.setText("Quản Lý Tài Khoản");
        jButton_QuanLyTaiKhoan.setBorder(null);
        jButton_QuanLyTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_QuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QuanLyTaiKhoanActionPerformed(evt);
            }
        });

        jButton_Logout.setBackground(new java.awt.Color(255, 102, 102));
        jButton_Logout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_Logout.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Logout.setText("Đăng Xuất");
        jButton_Logout.setBorderPainted(false);
        jButton_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_MenuLayout = new javax.swing.GroupLayout(jPanel_Menu);
        jPanel_Menu.setLayout(jPanel_MenuLayout);
        jPanel_MenuLayout.setHorizontalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_QuanLySach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_QuanLyBanDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_QuanLyPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jButton_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_QuanLyTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel_MenuLayout.setVerticalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton_QuanLySach, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_QuanLyBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_QuanLyPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_QuanLyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButton_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel_Content.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout jPanel_ContentLayout = new javax.swing.GroupLayout(jPanel_Content);
        jPanel_Content.setLayout(jPanel_ContentLayout);
        jPanel_ContentLayout.setHorizontalGroup(
            jPanel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        jPanel_ContentLayout.setVerticalGroup(
            jPanel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_QuanLyPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuanLyPhieuMuonActionPerformed
        cardLayout.show(jPanel_Content, "QuanLyPhieuMuon");
    }//GEN-LAST:event_jButton_QuanLyPhieuMuonActionPerformed

    private void jButton_QuanLySachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuanLySachActionPerformed
        cardLayout.show(jPanel_Content, "QuanLySach");
    }//GEN-LAST:event_jButton_QuanLySachActionPerformed

    private void jButton_ThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThongKeActionPerformed
        cardLayout.show(jPanel_Content, "ThongKe");
    }//GEN-LAST:event_jButton_ThongKeActionPerformed

    private void jButton_QuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuanLyTaiKhoanActionPerformed
        cardLayout.show(jPanel_Content, "QuanLyTaiKhoan");
    }//GEN-LAST:event_jButton_QuanLyTaiKhoanActionPerformed

    private void jButton_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogoutActionPerformed
        this.dispose();
        
        JFrame_Login loginFrame = new JFrame_Login();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_jButton_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new JFrame_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Logout;
    private javax.swing.JButton jButton_QuanLyBanDoc;
    private javax.swing.JButton jButton_QuanLyPhieuMuon;
    private javax.swing.JButton jButton_QuanLySach;
    private javax.swing.JButton jButton_QuanLyTaiKhoan;
    private javax.swing.JButton jButton_ThongKe;
    private javax.swing.JLabel jLabel_Welcome;
    private javax.swing.JPanel jPanel_Content;
    private javax.swing.JPanel jPanel_Menu;
    // End of variables declaration//GEN-END:variables
}
