/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.quanlythuvien.view.dialog;

import com.mycompany.quanlythuvien.view.dialog.ChiTietBanSaoDialog;
import com.mycompany.quanlythuvien.controller.BanSaoController;
import com.mycompany.quanlythuvien.model.BanSao;
import java.util.List;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class DanhSachBanSaoDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DanhSachBanSaoDialog.class.getName());
    private String isbn; //id cua sach goc
    private BanSaoController banSaoController = new BanSaoController();
    private Integer lastMaBanSao = null;
    private int pageSize = 10;
    private Stack<Integer> cursorStack = new Stack<>();
    /**
     * Creates new form DanhSachBanSaoDialog
     */
    public DanhSachBanSaoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public DanhSachBanSaoDialog(java.awt.Frame parent, boolean modal, String isbn) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.isbn = isbn;
        lblTieuDe.setText("Danh sách bản sao của sách: " + isbn);
        loadBanSao();
    }

    private void loadBanSaoPage(Integer cursor) {
        try {
            List<BanSao> list = banSaoController.getPage(isbn, pageSize, cursor);
            DefaultTableModel model = (DefaultTableModel) tblBanSao.getModel();
            model.setRowCount(0);
            
            for (BanSao b : list) {
                model.addRow(new Object[]{
                        b.getMaBanSao(),
                        b.getSoThuTuTrongKho(),
                        b.getTinhTrang(),
                        b.getNgayNhapKho(),
                        b.getViTriLuuTru()     
                });
            }
            
            if (!list.isEmpty()) {
                lastMaBanSao = list.get(list.size() - 1).getMaBanSao();
            }
            
            btnBSSau.setEnabled(list.size() == pageSize);
            btnBSTruoc.setEnabled(!cursorStack.isEmpty());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải danh sách bản sao: " + e.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBanSao = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnBSTruoc = new javax.swing.JButton();
        btnBSSau = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTieuDe.setText("Danh sách bản sao của sách:");
        jPanel1.add(lblTieuDe);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        tblBanSao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblBanSao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Bản Sao", "Số Thứ Tự", "Tình Trạng", "Ngày Nhập", "Vị Trí Lưu Trữ"
            }
        ));
        jScrollPane1.setViewportView(tblBanSao);

        jPanel4.add(jScrollPane1);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        btnBSTruoc.setText("Trước");
        btnBSTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBSTruocActionPerformed(evt);
            }
        });
        jPanel5.add(btnBSTruoc);

        btnBSSau.setText("Sau");
        btnBSSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBSSauActionPerformed(evt);
            }
        });
        jPanel5.add(btnBSSau);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem);

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSua);

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa);

        btnDong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });
        jPanel2.add(btnDong);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        new ChiTietBanSaoDialog(this, true, isbn, null).setVisible(true);
        loadBanSao();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int row = tblBanSao.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 bản sao để sửa!");
            return;
        }
        
        int maBanSao = (int) tblBanSao.getValueAt(row, 0);
        try {
            BanSao b = banSaoController.findById(maBanSao);
            new ChiTietBanSaoDialog(this, true, isbn, b).setVisible(true);
            loadBanSao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải bản sao: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tblBanSao.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 bản sao để xóa!");
            return;
        }
        int maBanSao = (int) tblBanSao.getValueAt(row, 0);
        if (JOptionPane.showConfirmDialog(this, "Xóa bản sao này?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                banSaoController.delete(maBanSao);
                loadBanSao();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    
    private void btnBSTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBSTruocActionPerformed
        // TODO add your handling code here:
        if (!cursorStack.isEmpty()) {
            Integer prevCursor = cursorStack.pop();
            loadBanSaoPage(prevCursor);
        }
    }//GEN-LAST:event_btnBSTruocActionPerformed

    private void loadBanSao() {
        cursorStack.clear();
        lastMaBanSao = null;
        loadBanSaoPage(lastMaBanSao);
    }
    
    private void btnBSSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBSSauActionPerformed
        // TODO add your handling code here:
        if (lastMaBanSao != null) {
            cursorStack.push(lastMaBanSao);
        }
        loadBanSaoPage(lastMaBanSao);
    }//GEN-LAST:event_btnBSSauActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DanhSachBanSaoDialog dialog = new DanhSachBanSaoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBSSau;
    private javax.swing.JButton btnBSTruoc;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JTable tblBanSao;
    // End of variables declaration//GEN-END:variables
}
