/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.quanlythuvien.view.dialog;

import com.mycompany.quanlythuvien.controller.BanSaoController;
import com.mycompany.quanlythuvien.model.TaiKhoan;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ThemHangLoatBanSaoDialog extends javax.swing.JDialog {
    private String isbn;
    private TaiKhoan currentUser;
    private BanSaoController banSaoController = new BanSaoController();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ThemHangLoatBanSaoDialog.class.getName());
    private final String DATE_FORMAT = "dd/MM/yyyy";
    /**
     * Creates new form ThemHangLoatBanSaoDialog
     */
    public ThemHangLoatBanSaoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public ThemHangLoatBanSaoDialog(java.awt.Dialog parent, boolean modal, String isbn, TaiKhoan currentUser) {
        super(parent, modal);
        this.isbn = isbn;
        this.currentUser = currentUser;
        initComponents();
        initData(); // Khởi tạo dữ liệu ban đầu
        setLocationRelativeTo(parent);
    }
    
    private void initData() {
        lblTieuDe.setText("Thêm hàng loạt bản sao cho sách: " + this.isbn);
        txtISBN.setText(this.isbn);
        txtISBN.setEditable(false);
        
        txtCreatedBy.setText(this.currentUser.getEmail());
        txtCreatedBy.setEditable(false);
        txtTinhTrang.setText("Tốt");

    // START: Tự động điền ngày nhập kho từ hệ thống (cho người dùng xem)
        LocalDate ngayHienTai = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern(DATE_FORMAT);
        txtNgayNhapKho.setText(ngayHienTai.format(formatter));
        
        txtNgayNhapKho.setEditable(false);
        txtNgayNhapKho.setDisabledTextColor(Color.BLACK);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTao = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtISBN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        lblSoThuTu = new javax.swing.JLabel();
        txtSoThuTu = new javax.swing.JTextField();
        lblTinhTrang = new javax.swing.JLabel();
        txtTinhTrang = new javax.swing.JTextField();
        lblNgayNhapKho = new javax.swing.JLabel();
        txtNgayNhapKho = new javax.swing.JTextField();
        lblViTri = new javax.swing.JLabel();
        txtViTri = new javax.swing.JTextField();
        lblCreatedBy = new javax.swing.JLabel();
        txtCreatedBy = new javax.swing.JTextField();
        lblCreatedAt = new javax.swing.JLabel();
        txtCreatedAt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTieuDe.setText("Thêm hàng loạt bản sao");
        jPanel1.add(lblTieuDe);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnTao.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnTao.setText("[+] Tạo hàng loạt");
        btnTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoActionPerformed(evt);
            }
        });
        jPanel2.add(btnTao);

        btnHuy.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnHuy.setText("[×] Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel2.add(btnHuy);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        txtISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtISBN.setPreferredSize(new java.awt.Dimension(200, 26));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("lblISBN");

        lblSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong.setText("Số lượng bản sao cần tạo:");

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblSoThuTu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoThuTu.setText("Số thứ tự trong kho:");

        txtSoThuTu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTinhTrang.setText("Tình trạng:");

        txtTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTinhTrang.setToolTipText("Nhập một trong các giá trị: Tốt, Cũ, Rất Cũ, Hỏng");

        lblNgayNhapKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNgayNhapKho.setText("Ngày nhập kho:");

        txtNgayNhapKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblViTri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViTri.setText("Vị trí lưu trữ:");

        txtViTri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCreatedBy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCreatedBy.setText("Người tạo:");

        txtCreatedBy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCreatedAt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCreatedAt.setText("Ngày tạo:");

        txtCreatedAt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoLuong)
                    .addComponent(lblSoThuTu)
                    .addComponent(lblTinhTrang)
                    .addComponent(lblNgayNhapKho)
                    .addComponent(lblViTri)
                    .addComponent(lblCreatedBy)
                    .addComponent(lblCreatedAt)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCreatedBy, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtViTri)
                    .addComponent(txtNgayNhapKho)
                    .addComponent(txtTinhTrang)
                    .addComponent(txtCreatedAt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong)
                    .addComponent(txtSoThuTu))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuong)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoThuTu)
                    .addComponent(txtSoThuTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTinhTrang)
                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayNhapKho)
                    .addComponent(txtNgayNhapKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViTri)
                    .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreatedBy)
                    .addComponent(txtCreatedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreatedAt)
                    .addComponent(txtCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoActionPerformed
        // TODO add your handling code here:
        try {
            String sSoLuong = txtSoLuong.getText().trim();
            String sSoThuTu = txtSoThuTu.getText().trim();
            String viTri = txtViTri.getText().trim();
            String tinhTrang = txtTinhTrang.getText().trim();
            
            if (sSoLuong.isEmpty() || sSoThuTu.isEmpty() || viTri.isEmpty() || tinhTrang.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Vui lòng nhập đầy đủ Số lượng, Số thứ tự bắt đầu, Tình trạng và Vị trí lưu trữ!",
                        "Thiếu dữ liệu", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Validate TinhTrang
            if (!tinhTrang.equals("Tốt") && !tinhTrang.equals("Cũ") && 
                !tinhTrang.equals("Rất Cũ") && !tinhTrang.equals("Hỏng")) {
                JOptionPane.showMessageDialog(this, 
                    "Tình trạng phải là một trong các giá trị: Tốt, Cũ, Rất Cũ, Hỏng", 
                    "Lỗi Validation", 
                    JOptionPane.ERROR_MESSAGE);
                txtTinhTrang.requestFocus();
                return;
            }
            
            int soLuong;
            int soThuTuBatDau;
            try {
                soLuong = Integer.parseInt(sSoLuong);
                soThuTuBatDau = Integer.parseInt(sSoThuTu);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                    "Số lượng và Số thứ tự phải là số nguyên!",
                    "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (soLuong <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng bản sao phải lớn hơn 0.", 
                        "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int insertedCnt = banSaoController.insertBatch(isbn, soLuong, soThuTuBatDau, tinhTrang, viTri, currentUser.getEmail());
            
            JOptionPane.showMessageDialog(this,
                    "Đã thêm thành công " + insertedCnt + " bản sao của sách " + this.isbn + ".",
                    "Thành công", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Lỗi khi tạo bản sao: " + e.getMessage(),
                    "Lỗi Database/Server", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTaoActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ThemHangLoatBanSaoDialog dialog = new ThemHangLoatBanSaoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnTao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCreatedAt;
    private javax.swing.JLabel lblCreatedBy;
    private javax.swing.JLabel lblNgayNhapKho;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblSoThuTu;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblTinhTrang;
    private javax.swing.JLabel lblViTri;
    private javax.swing.JTextField txtCreatedAt;
    private javax.swing.JTextField txtCreatedBy;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNgayNhapKho;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoThuTu;
    private javax.swing.JTextField txtTinhTrang;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables
}
