/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.quanlythuvien.dialog;

import com.mycompany.quanlythuvien.dao.BanSaoDAO;
import com.mycompany.quanlythuvien.model.BanSao;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ChiTietBanSaoDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChiTietBanSaoDialog.class.getName());
    private String isbn;
    private BanSao bansao; //null -> them moi
    private BanSaoDAO dao = new BanSaoDAO();
    /**
     * Creates new form ChiTietBanSaoDialog
     */
    public ChiTietBanSaoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public ChiTietBanSaoDialog(java.awt.Dialog parent, boolean modal, String isbn, BanSao bansao){
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.isbn = isbn;
        this.bansao = bansao;
        
        txtMaBanSao.setEditable(false);
        txtISBN.setEditable(false);
        txtISBN.setText(isbn);
        
        if (bansao != null) {
            txtMaBanSao.setText(String.valueOf(bansao.getMaBanSao()));
            txtSoThuTuTrongKho.setText(String.valueOf(bansao.getSoThuTuTrongKho()));
            txtTinhTrang.setText(bansao.getTinhTrang());
            txtNgayNhapKho.setText((bansao.getNgayNhapKho() != null) ? bansao.getNgayNhapKho().toString() : "");
            txtViTriLuuTru.setText(bansao.getViTriLuuTru());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblMaBanSao = new javax.swing.JLabel();
        txtMaBanSao = new javax.swing.JTextField();
        lblISBN = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        lblSoThuTuTrongKho = new javax.swing.JLabel();
        txtSoThuTuTrongKho = new javax.swing.JTextField();
        lblTinhTrang = new javax.swing.JLabel();
        txtTinhTrang = new javax.swing.JTextField();
        lblNgayNhapKho = new javax.swing.JLabel();
        txtNgayNhapKho = new javax.swing.JTextField();
        lblViTriLuuTru = new javax.swing.JLabel();
        txtViTriLuuTru = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTieuDe.setText("Chi tiết bản sao");
        jPanel1.add(lblTieuDe);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel3.add(btnLuu);

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel3.add(btnHuy);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(6, 2));

        lblMaBanSao.setText("Mã bản sao:");
        jPanel2.add(lblMaBanSao);
        jPanel2.add(txtMaBanSao);

        lblISBN.setText("ISBN:");
        jPanel2.add(lblISBN);
        jPanel2.add(txtISBN);

        lblSoThuTuTrongKho.setText("Số thứ tự trong kho:");
        jPanel2.add(lblSoThuTuTrongKho);
        jPanel2.add(txtSoThuTuTrongKho);

        lblTinhTrang.setText("Tình trạng:");
        jPanel2.add(lblTinhTrang);
        jPanel2.add(txtTinhTrang);

        lblNgayNhapKho.setText("Ngày nhập kho:");
        jPanel2.add(lblNgayNhapKho);
        jPanel2.add(txtNgayNhapKho);

        lblViTriLuuTru.setText("Vị trí lưu trữ:");
        jPanel2.add(lblViTriLuuTru);
        jPanel2.add(txtViTriLuuTru);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        try {
            String tinhTrang = txtTinhTrang.getText().trim();
            String viTri = txtViTriLuuTru.getText().trim();
            int soThuTu = Integer.parseInt(txtSoThuTuTrongKho.getText().trim());
            LocalDate ngayNhap = null;
            if (!txtNgayNhapKho.getText().isEmpty()) {
                try {
                    ngayNhap = LocalDate.parse(txtNgayNhapKho.getText().trim());
                } catch (DateTimeParseException ex){
                    JOptionPane.showMessageDialog(this, "Ngày nhập không hợp lệ! Định dạng: yyyy-MM-dd");
                    return;
                }
            }
                    
            BanSao b = new BanSao(
                    (bansao != null) ? bansao.getMaBanSao() : 0,
                    isbn,
                    soThuTu,
                    tinhTrang,
                    ngayNhap,
                    viTri
            );
            
            if (bansao == null) dao.insert(b);
            else dao.update(b);
            
            JOptionPane.showMessageDialog(this, "Lưu thành công");
            dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số thứ tự trong kho phải là số nguyên!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi lưu: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ChiTietBanSaoDialog dialog = new ChiTietBanSaoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblMaBanSao;
    private javax.swing.JLabel lblNgayNhapKho;
    private javax.swing.JLabel lblSoThuTuTrongKho;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblTinhTrang;
    private javax.swing.JLabel lblViTriLuuTru;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtMaBanSao;
    private javax.swing.JTextField txtNgayNhapKho;
    private javax.swing.JTextField txtSoThuTuTrongKho;
    private javax.swing.JTextField txtTinhTrang;
    private javax.swing.JTextField txtViTriLuuTru;
    // End of variables declaration//GEN-END:variables
}
