/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.quanlythuvien.dialog;

import com.mycompany.quanlythuvien.dao.NhaXuatBanDAO;
import com.mycompany.quanlythuvien.dao.SachDAO;
import com.mycompany.quanlythuvien.dao.TacGiaDAO;
import com.mycompany.quanlythuvien.dao.TheLoaiDAO;
import com.mycompany.quanlythuvien.model.NhaXuatBan;
import com.mycompany.quanlythuvien.model.Sach;
import com.mycompany.quanlythuvien.model.TacGia;
import com.mycompany.quanlythuvien.model.TheLoai;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ThongTinSachDialog extends javax.swing.JDialog {
    private Sach sach;
    private boolean isEditMode;
    private boolean isViewMode;

    private List<TacGia> listTacGia;
    private List<TheLoai> listTheLoai;
    private List<NhaXuatBan> listNXB;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ThongTinSachDialog.class.getName());

    /**
     * Creates new form ThongTinSachDialog
     */
    public ThongTinSachDialog(java.awt.Frame parent, boolean modal, Sach sach, boolean isEditMode, boolean isViewMode) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        this.sach = sach;
        this.isEditMode = isEditMode;
        this.isViewMode = isViewMode;
        
        loadComboBoxes();
        
        if (sach != null) {
            fillForm();
            if (isViewMode) {
                setViewMode();
            }
        } 
    }
    public ThongTinSachDialog(javax.swing.JFrame parent, boolean modal) {
        this((java.awt.Frame) parent, modal, null, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblISBN = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        lblTenSach = new javax.swing.JLabel();
        lblMaTacGia = new javax.swing.JLabel();
        lblMaTheLoai = new javax.swing.JLabel();
        lblNamXuatBan = new javax.swing.JLabel();
        lblDinhDang = new javax.swing.JLabel();
        lblGiaBia = new javax.swing.JLabel();
        lblSoTrang = new javax.swing.JLabel();
        lblSoLuongTon = new javax.swing.JLabel();
        lblMoTa = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        cboMaTheLoai = new javax.swing.JComboBox<>();
        txtDinhDang = new javax.swing.JTextField();
        txtGiaBia = new javax.swing.JTextField();
        txtSoTrang = new javax.swing.JTextField();
        txtSoLuongTon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblMaNXB = new javax.swing.JLabel();
        cboMaNXB = new javax.swing.JComboBox<>();
        txtNamXuatBan = new javax.swing.JTextField();
        cboMaTacGia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin sách");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        lblISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblISBN.setText("ISBN:");

        txtISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTenSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTenSach.setText("Tên sách:");

        lblMaTacGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaTacGia.setText("Tác giả");

        lblMaTheLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaTheLoai.setText("Thể loại");

        lblNamXuatBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNamXuatBan.setText("Năm xuất bản");

        lblDinhDang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDinhDang.setText("Định dạng:");

        lblGiaBia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGiaBia.setText("Giá bìa:");

        lblSoTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoTrang.setText("Số trang:");

        lblSoLuongTon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuongTon.setText("Số lượng tồn:");

        lblMoTa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMoTa.setText("Mô tả: ");

        txtTenSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSachActionPerformed(evt);
            }
        });

        cboMaTheLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboMaTheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDinhDang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtGiaBia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGiaBia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaBiaActionPerformed(evt);
            }
        });

        txtSoTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoTrangActionPerformed(evt);
            }
        });

        txtSoLuongTon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoLuongTon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongTonActionPerformed(evt);
            }
        });

        txtMoTa.setColumns(20);
        txtMoTa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMoTa.setLineWrap(true);
        txtMoTa.setRows(5);
        txtMoTa.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtMoTa);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        lblMaNXB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaNXB.setText("Nhà xuất bản:");

        cboMaNXB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboMaNXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtNamXuatBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cboMaTacGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboMaTacGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDinhDang, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGiaBia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLuu)
                            .addComponent(lblMaNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDinhDang, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtISBN, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cboMaTheLoai, javax.swing.GroupLayout.Alignment.LEADING, 0, 190, Short.MAX_VALUE)
                        .addComponent(txtTenSach)
                        .addComponent(txtGiaBia)
                        .addComponent(txtSoTrang)
                        .addComponent(txtSoLuongTon, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(cboMaNXB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNamXuatBan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cboMaTacGia, javax.swing.GroupLayout.Alignment.LEADING, 0, 190, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnHuy)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMaTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMaTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDinhDang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDinhDang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGiaBia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaBia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btnLuu)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnHuy)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadComboBoxes() {
        try {
            //load tac gia
            TacGiaDAO tgDAO = new TacGiaDAO();
            listTacGia = tgDAO.getAll();
            cboMaTacGia.removeAllItems();
            cboMaTacGia.addItem("Không xác định");
            for (var tg : listTacGia) {
                cboMaTacGia.addItem(tg.getTenTacGia()); //hien thi ten tac gia
            }
            
            //load NXB
            NhaXuatBanDAO nxbDAO = new NhaXuatBanDAO();
            listNXB = nxbDAO.getAll();
            cboMaNXB.removeAllItems();
            cboMaNXB.addItem("Không xác định");
            for (var nxb : listNXB) {
                cboMaNXB.addItem(nxb.getTenNXB());
            }
            
            //load the loai
            TheLoaiDAO tlDAO = new TheLoaiDAO();
            listTheLoai = tlDAO.getAll();
            cboMaTheLoai.removeAllItems();
            cboMaTheLoai.addItem("Không xác định");
            for (var tl : listTheLoai) {
                cboMaTheLoai.addItem(tl.getTenTheLoai());
            }
            
            //so luong ton ko cho chinh sua (trigger tu cap nhat)
            txtSoLuongTon.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi load dữ liệu combobox: " + e.getMessage());
        }
    }
    
    private void fillForm() {
        txtISBN.setText(sach.getISBN());
        txtTenSach.setText(sach.getTenSach());
        txtNamXuatBan.setText(String.valueOf(sach.getNamXuatBan()));
        txtGiaBia.setText(String.valueOf(sach.getGiaBia()));
        txtSoTrang.setText(String.valueOf(sach.getSoTrang()));
        txtDinhDang.setText(sach.getDinhDang());
        txtMoTa.setText(sach.getMoTa());
        txtSoLuongTon.setText(String.valueOf(sach.getSoLuongTon()));
        
        //chon dung combobox theo ID
        selectComboBoxById(listTacGia, cboMaTacGia, sach.getMaTacGia());
        selectComboBoxById(listTheLoai, cboMaTheLoai, sach.getMaTheLoai());
        selectComboBoxById(listNXB, cboMaNXB, sach.getMaNXB());
    }
    
    private void setViewMode() {
        txtISBN.setEditable(false);
        txtTenSach.setEditable(false);
        txtNamXuatBan.setEditable(false);
        txtGiaBia.setEditable(false);
        txtSoTrang.setEditable(false);
        txtDinhDang.setEditable(false);
        txtMoTa.setEditable(false);
        txtSoLuongTon.setEditable(false);

        cboMaTacGia.setEnabled(false);
        cboMaTheLoai.setEnabled(false);
        cboMaNXB.setEnabled(false);

        btnLuu.setVisible(false);
        btnHuy.setText("Đóng");
    }
    
    private <T> void selectComboBoxById(List<T> list, JComboBox<String> combo, int id) {
        for (int i = 0; i < list.size(); i++) {
            Object item = list.get(i);
            if ((item instanceof TacGia && ((TacGia) item).getMaTacGia() == id) ||
                (item instanceof TheLoai && ((TheLoai) item).getMaTheLoai() == id) ||
                (item instanceof NhaXuatBan && ((NhaXuatBan) item).getMaNXB() == id)) {
                combo.setSelectedIndex(i);
                return;
            }
        }
    }
    
    private void txtTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSachActionPerformed

    private void txtGiaBiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaBiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaBiaActionPerformed

    private void txtSoTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoTrangActionPerformed

    private void txtSoLuongTonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongTonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongTonActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        try {
            if (sach == null) sach = new Sach();

            sach.setISBN(txtISBN.getText().trim());
            sach.setTenSach(txtTenSach.getText().trim());
            
            //trong -> set null
            String namStr = txtNamXuatBan.getText().trim();
            sach.setNamXuatBan(namStr.isEmpty() ? null : Integer.parseInt(namStr));
            
            String giaStr = txtGiaBia.getText().trim();
            sach.setGiaBia(giaStr.isEmpty() ? null : new BigDecimal(giaStr));
            
            String trangStr = txtSoTrang.getText().trim();
            sach.setSoTrang(trangStr.isEmpty() ? null : Integer.parseInt(trangStr));
            
            sach.setDinhDang(txtDinhDang.getText().trim().isEmpty() ? "Bản in" : txtDinhDang.getText().trim());
            sach.setMoTa(txtMoTa.getText().trim());
            
            sach.setSoLuongTon(null); //trigger tu update => bo qua

            int indexTG = cboMaTacGia.getSelectedIndex();
            int indexNXB = cboMaNXB.getSelectedIndex();
            int indexTL = cboMaTheLoai.getSelectedIndex();

            sach.setMaTacGia((indexTG <= 0) ? null : listTacGia.get(indexTG - 1).getMaTacGia());
            sach.setMaNXB((indexNXB <= 0) ? null : listNXB.get(indexNXB - 1).getMaNXB());
            sach.setMaTheLoai((indexTL <= 0) ? null : listTheLoai.get(indexTL - 1).getMaTheLoai());

            if (sach.getDinhDang().trim().equalsIgnoreCase("Bản in") && (sach.getSoTrang() == null || sach.getSoTrang() < 0)) {
                JOptionPane.showMessageDialog(this, "Sách bản in phải có số trang > 0!");
                return;
            } else {
                sach.setSoTrang(null);
            }
            
            //luu xuong database
            SachDAO dao = new SachDAO();
            if (isEditMode) {
                dao.update(sach);
                JOptionPane.showMessageDialog(this, "Cập nhật sách thành công!");
            } else {
                dao.insert(sach);
                JOptionPane.showMessageDialog(this, "Thêm sách mới thành công!");
            }
            dispose();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng số!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu sách: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed
    public Sach getSach() {
        return sach;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ThongTinSachDialog dialog = new ThongTinSachDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cboMaNXB;
    private javax.swing.JComboBox<String> cboMaTacGia;
    private javax.swing.JComboBox<String> cboMaTheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDinhDang;
    private javax.swing.JLabel lblGiaBia;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblMaNXB;
    private javax.swing.JLabel lblMaTacGia;
    private javax.swing.JLabel lblMaTheLoai;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblNamXuatBan;
    private javax.swing.JLabel lblSoLuongTon;
    private javax.swing.JLabel lblSoTrang;
    private javax.swing.JLabel lblTenSach;
    private javax.swing.JTextField txtDinhDang;
    private javax.swing.JTextField txtGiaBia;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtNamXuatBan;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JTextField txtSoTrang;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
